#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/greenflash-ai/go,github.com/stainless-sdks/greenflash-public-api-go"

REPLACEMENT="${1:-"../Greenflash-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/greenflash-ai/go="$REPLACEMENT"
go mod tidy -e
