#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/greenflash-ai/go,github.com/stainless-sdks/greenflash-public-api-go"

go run ./cmd/greenflash-public-api "$@"
